//! # D-Bus interface proxy for: `org.mpris.MediaPlayer2.Player`
//!
//! This code was generated by `zbus-xmlgen` `5.1.0` from D-Bus introspection data.
//! Source: `Interface '/org/mpris/MediaPlayer2' from service 'org.mpris.MediaPlayer2.firefox.instance_1_100' on system bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::PropertiesProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PeerProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use std::{collections::HashMap, time::Duration};

use clap::ValueEnum;
use serde::{Deserialize, Serialize};
use zbus::{
    proxy,
    zvariant::{DeserializeDict, OwnedValue, SerializeDict, Signature, Type, Value, as_value},
};

#[derive(Debug, Deserialize, Default, Type)]
#[zvariant(signature = "dict")]
#[serde(default)]
pub struct Metadata {
    #[serde(rename = "mpris:length", with = "as_value")]
    pub length: MicroDuration,
    #[serde(rename = "mpris:artUrl", with = "as_value")]
    pub art: String,
    #[serde(rename = "xesam:title", with = "as_value")]
    pub title: String,
    #[serde(rename = "xesam:album", with = "as_value")]
    pub album: String,
    #[serde(rename = "xesam:artist", with = "as_value")]
    pub artists: Vec<String>,
    // #[zvariant(rename = "xesam:artist")]
    // pub url: String,
}

#[derive(Deserialize, Default, Debug)]
#[serde(from = "i64")]
pub struct MicroDuration(pub Duration);

impl From<i64> for MicroDuration {
    fn from(value: i64) -> Self {
        MicroDuration(Duration::from_micros(value as u64))
    }
}

impl From<OwnedValue> for MicroDuration {
    fn from(value: OwnedValue) -> Self {
        MicroDuration(Duration::from_micros(convert::<i64>(value).unwrap() as u64))
    }
}

impl Type for MicroDuration {
    const SIGNATURE: &'static zbus::zvariant::Signature = &Signature::I64;
}

#[derive(
    Serialize,
    Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    PartialOrd,
    Eq,
    Ord,
    Type,
    Value,
    OwnedValue,
    ValueEnum,
)]
#[zvariant(signature = "s")]
pub enum PlaybackStatus {
    Playing = 0,
    Paused = 1,
    Stopped = 2,
}

impl PlaybackStatus {
    pub fn button(self) -> &'static str {
        match self {
            PlaybackStatus::Playing => "||",
            PlaybackStatus::Paused => "❙❯",
            PlaybackStatus::Stopped => "██",
        }
    }
}

impl TryFrom<OwnedValue> for Metadata {
    type Error = zbus::zvariant::Error;

    fn try_from(value: OwnedValue) -> Result<Self, Self::Error> {
        let mut map = HashMap::<String, OwnedValue>::try_from(value)?;

        Ok(Metadata {
            length: map
                .remove("mpris:length")
                .and_then(convert)
                .unwrap_or_default(),
            art: map
                .remove("mpris:artUrl")
                .and_then(convert)
                .unwrap_or_default(),
            title: map
                .remove("xesam:title")
                .and_then(convert)
                .unwrap_or_default(),
            album: map
                .remove("xesam:album")
                .and_then(convert)
                .unwrap_or_default(),
            artists: map
                .remove("xesam:artist")
                .and_then(convert)
                .unwrap_or_default(),
            // url: map
            //     .remove("xesam:url")
            //     .and_then(convert)
            //     .unwrap_or_default(),
        })
    }
}

fn convert<T: TryFrom<OwnedValue>>(v: OwnedValue) -> Option<T> {
    T::try_from(v).ok()
}

#[proxy(
    interface = "org.mpris.MediaPlayer2.Player",
    default_path = "/org/mpris/MediaPlayer2",
    gen_blocking = true
)]
pub trait Player {
    /// Next method
    fn next(&self) -> zbus::Result<()>;

    /// OpenUri method
    fn open_uri(&self, Uri: &str) -> zbus::Result<()>;

    /// Pause method
    fn pause(&self) -> zbus::Result<()>;

    /// Play method
    fn play(&self) -> zbus::Result<()>;

    /// PlayPause method
    fn play_pause(&self) -> zbus::Result<()>;

    /// Previous method
    fn previous(&self) -> zbus::Result<()>;

    /// Seek method
    fn seek(&self, Offset: i64) -> zbus::Result<()>;

    /// SetPosition method
    fn set_position(
        &self,
        TrackId: &zbus::zvariant::ObjectPath<'_>,
        Position: i64,
    ) -> zbus::Result<()>;

    /// Stop method
    fn stop(&self) -> zbus::Result<()>;

    /// Seeked signal
    #[zbus(signal)]
    fn seeked(&self, Position: i64) -> zbus::Result<()>;

    /// CanControl property
    #[zbus(property)]
    fn can_control(&self) -> zbus::Result<bool>;

    /// CanGoNext property
    #[zbus(property)]
    fn can_go_next(&self) -> zbus::Result<bool>;

    /// CanGoPrevious property
    #[zbus(property)]
    fn can_go_previous(&self) -> zbus::Result<bool>;

    /// CanPause property
    #[zbus(property)]
    fn can_pause(&self) -> zbus::Result<bool>;

    /// CanPlay property
    #[zbus(property)]
    fn can_play(&self) -> zbus::Result<bool>;

    /// CanSeek property
    #[zbus(property)]
    fn can_seek(&self) -> zbus::Result<bool>;

    /// MaximumRate property
    #[zbus(property)]
    fn maximum_rate(&self) -> zbus::Result<f64>;

    /// Metadata property
    #[zbus(property)]
    fn metadata(&self) -> zbus::Result<Metadata>;

    /// MinimumRate property
    #[zbus(property)]
    fn minimum_rate(&self) -> zbus::Result<f64>;

    /// PlaybackStatus property
    #[zbus(property)]
    fn playback_status(&self) -> zbus::Result<PlaybackStatus>;

    /// Position property
    #[zbus(property)]
    fn position(&self) -> zbus::Result<i64>;

    /// Rate property
    #[zbus(property)]
    fn rate(&self) -> zbus::Result<f64>;
    #[zbus(property)]
    fn set_rate(&self, value: f64) -> zbus::Result<()>;

    /// Volume property
    #[zbus(property)]
    fn volume(&self) -> zbus::Result<f64>;
    #[zbus(property)]
    fn set_volume(&self, value: f64) -> zbus::Result<()>;
}
