component_type: !Group
  components:
    - component_type: !NiriInfo
      constraint: !Fill 1
      block:
        title: FOCUS

    - component_type: !Visualizer
      constraint: !Length 35
      block:
        title: VISUALIZER

    - component_type: !Date
        elements:
          - name: DAY
            fmt: "%a"
          - name: TIME
            fmt: "%R"
          - name: DATE
            fmt: "%d.%m.%Y"
      constraint: !Length 30
      block:
        title: CLOCK

    - component_type: !NowPlaying
        preference:
          players:
            - Cider
            - Mozilla firefox
          at_least:
            !Playing
      constraint: !Length 70
      block:
        title: NOW PLAYING

    - component_type: !Cpu
      constraint: !Length 30
      block:
        title: CPU

    - component_type: !Ram
      constraint: !Length 25
      block:
        title: RAM

    - component_type: !Net
        adapter: enp42s0
      constraint: !Length 20
      block:
        title: NET
